### ISSUE TITLE
CRDs not recognised

### ISSUE THREAD

**Issue by silvpol** [mingfang/terraform-provider-k8s#10]
I have tried to use plugin to provision cert-manager but encountered two likely related issues:
1. Extracting TF files from YAML files seems to work but after applying them the resulting **cert-manager** installation fails to provision any certs. For testing after deployment I have used the file supplied by cert manager [troubleshooting guide](https://docs.cert-manager.io/en/release-0.7/getting-started/troubleshooting.html). Applying the same installation file manually with kubectl works fine.
2. Trying to extract TF files from troubleshooting YAML code in the cert-manager troubleshooting guide fails to extract Issuer and Certificate CRDs.
```
2020/01/14 20:44:37 v1/cert_manager_test-namespace.tf
2020/01/14 20:44:37 No Model For: Issuer cert-manager.io/v1alpha2, Kind=Issuer
2020/01/14 20:44:37 No Model For: Certificate cert-manager.io/v1alpha2, Kind=Certificate
```
I'm also getting some spurious diffs in CRD resources pointing to the same underlying issue. I have tested with plugin 0.1.2 and 0.1.3 and both exhibit that behaviour.

I have attached **cert-manager** 0.12 install YAML file and a test file.

[cert-manager_fixed.yaml.zip](https://github.com/mingfang/terraform-provider-k8s/files/4061352/cert-manager_fixed.yaml.zip)
[cert-manager-test.yaml.zip](https://github.com/mingfang/terraform-provider-k8s/files/4061356/cert-manager-test.yaml.zip)

I have used the script below for TF extraction. It reads original installation yaml file and applies two tweaks for Kubernetes 1.14

```
#!/usr/bin/env bash

FILE_IN=cert-manager.yaml
FILE_OUT=cert-manager_fixed.yaml
cat ${FILE_IN} > ${FILE_OUT}

# avoid perma-diffs before Kubernetes 1.16
sed -i '' -e "/x-kubernetes-preserve-unknown-fields/ d" ${FILE_OUT}

# disable validation on cert-manager namespace to get it to start
sed -i '' -e '/kind: Namespace/ {
    N
    /metadata:/ {
        N
        /name: cert-manager/ {
            a\
            \  labels:
            a\
            \    certmanager.k8s.io/disable-validation: "true"
        }
    }
}' ${FILE_OUT}

# make version based dir for output
DIR=$(sed -n -e 's/.*cert-manager-controller:\(v[0-9.]*\).*/\1/p' ${FILE_OUT})
[[ "$DIR" != "" ]] || exit 500
[[ -d ${DIR} ]] || mkdir ${DIR} || exit 500

unset KUBECONFIG
kubectl config view --minify --flatten --context=docker-desktop > kubeconfig || exit 401
KUBECONFIG=kubeconfig

docker pull registry.rebelsoft.com/terraform-provider-k8s
docker run \
    -v `pwd`/kubeconfig:/kubeconfig \
    -e KUBECONFIG=/kubeconfig \
    -v `pwd`:/docker \
    -w /docker \
    --rm -it registry.rebelsoft.com/terraform-provider-k8s extractor \
    -filename ${FILE_OUT} -dir ${DIR}

# add dependency on namespace resource to fix apply errors
sed -i '' -e 's/namespace = "cert-manager"/namespace = k8s_core_v1_namespace.cert_manager.metadata[0].name/' ${DIR}/*.tf

rm kubeconfig
```

**Comment by mingfang** [comment]
I already have the cert-manager module available here 
https://github.com/mingfang/terraform-k8s-modules/tree/master/modules/cert-manager

The extraction script is here 
https://github.com/mingfang/terraform-k8s-modules/blob/master/modules/cert-manager/extract.sh

To use it you first have to apply just this TF file 
https://github.com/mingfang/terraform-k8s-modules/blob/master/examples/crd/cert-manager.tf
Note all CRDs must be applied separate from the resource creation TF files.

Finally an example of creating certs is here 
https://github.com/mingfang/terraform-k8s-modules/tree/master/examples/cert-manager

I will upgrade to cert-manager v0.12.0 soon.

**Comment by silvpol** [comment]
I have done some further testing and the **subresources** key is the culprit. Updating after deployment manually with `kubectl edit crd <crd_name>` to match orginal YAML file fixes issuing certificates. Plugin generates just an empty block during conversion.

I have exported cert-manager namespace after creating via kubect and file, after first apply via TF and after second apply via TF.

Via kubectl:
```
...
    subresources:
      status: {}
...
```

TF after first apply - **subresources** key missing altogether

TF after second apply:
```
...
    subresources: {}
...
```
 I have attached CRD dumps so that you can compare. [exports.zip](https://github.com/mingfang/terraform-provider-k8s/files/4062346/exports.zip)

**Comment by mingfang** [comment]
Please try to use my cert-manager module.
I use it in production so I know it works.

**Comment by silvpol** [comment]
Thanks, I'll test the module. Out of curiosity, your module doesn't include webhook, was there an issue you were trying to work around?

With regards to import of cert and issuer CRDs, is it expected behaviour or likely something on my end?

**Comment by mingfang** [comment]
Terraform's handling of empty fields is little different from kubernetes. But it should not make any difference whether there is an empty `subresource` or none at all.  I'll look into why it behaves differently when applying the second time.

As for the web hook I remember it had some issues before.
Things might be better in the latest release.
I'll look into it.

**Comment by mingfang** [comment]
I added the optional cert-manager/webhook module 
https://github.com/mingfang/terraform-k8s-modules/tree/master/modules/cert-manager/webhook

**Comment by silvpol** [comment]
I have tried the module you sugested against Docker Desktop and Google Cloud (both running Kubernetes 1.14) and I couldn't get it to work. I have used the example in the modules repo and this is what happened:

1. Tried to apply CRDs, it would complain about **preserve_unknown_fields** field not being recognised, commented them out
2. During applying CRDs the second time, the diff about **subresources** showed up.
3. Applied main module without webhook or example cert and tried to use test file from troubleshooting guide. - Cert would be stuck on certificate request stage.
```
Events:
  Type    Reason        Age   From          Message
  ----    ------        ----  ----          -------
  Normal  GeneratedKey  74m   cert-manager  Generated a new private key
  Normal  Requested     74m   cert-manager  Created new CertificateRequest resource "selfsigned-cert-2334779822"
```
After editing CDRs with **kubectl edit**, cert is issued within seconds:
```
Events:
  Type    Reason        Age   From          Message
  ----    ------        ----  ----          -------
  Normal  GeneratedKey  75m   cert-manager  Generated a new private key
  Normal  Requested     75m   cert-manager  Created new CertificateRequest resource "selfsigned-cert-2334779822"
  Normal  Issued        2s    cert-manager  Certificate issued successfully
```

4. Tried to apply cert from TF example module but plugin didn't recognise resources:
```
The provider provider.k8s does not support resource type
"k8s_cert_manager_io_v1alpha2_cluster_issuer".
The provider provider.k8s does not support resource type
"k8s_cert_manager_io_v1alpha2_certificate".
```
I have compared cert-manager 0.10.1 and 0.12.0 YAML files and the change is addition of **status: {}** inside **subresources** key. Unfortunately plugin doesn't allow specifying it so the only way to get it to work is to edit CRDs by hand after applying.

**Comment by mingfang** [comment]
> 1. Tried to apply CRDs, it would complain about **preserve_unknown_fields** field not being recognised, commented them out

This field comes from the origin cert-manager yaml but is not compatible with kubernetes v1.14
https://github.com/kubernetes/kubernetes/issues/82874

**Comment by mingfang** [comment]
@silvpol Please try https://github.com/mingfang/terraform-provider-k8s/releases/tag/v0.1.4
and update your copy of the cert-manager/crd module 
https://github.com/mingfang/terraform-k8s-modules/tree/master/modules/cert-manager/crd

**Comment by silvpol** [comment]
Thank you very much. I could succesfully deploy cert-manager and create test cert after the changes. As a bonus the subresources diff on second apply is gone.

I have tried creating cert & issuer using TF but same error about unknown resource still comes up. Extraction also fails from YAML for cert and issuer. Kubernetes 1.15 is now GA on Google Cloud so I will test with newer version to see if is starts working at that version.

**Comment by silvpol** [comment]
I have tested with 1.15 and now I can extract issuer and cert from YAML and then appply it succesfully.
I have noticed a change - the format of the spec field has changed from object to string so example module doesn't work anymore

```
  spec {
    self_signed = { "" = "" } //hack since TF does not allow empty values
  }
```
becomes
```
  spec = <<-JSON
    {
      "selfSigned": {}
    }
    JSON

```

**Comment by mingfang** [comment]
I'm glad things are working better.
CRDs has been undergoing major changes from version to version.
I documented some of the changes here https://github.com/mingfang/kubernetes-crd-test

If my cert-manager/crd modules works then you shouldn't have to do your own extraction.

**Comment by silvpol** [comment]
I have been using your module as reference to validate and compare against our setup. We have some custom requirements like using private registry and private cluster and need to do some processing before deploying. Not sure my modifications would be widely reusable hence not opening a PR.
