### ISSUE TITLE
Outdated link, how to use provider locally?

### ISSUE THREAD

**Issue by pmioduszewski** [mingfang/terraform-provider-k8s#17]
Hello, 
https://www.terraform.io/docs/configuration/providers.html#third-party-plugins seems to be outdated, I can't find any info how to use terraform-provider-k8s locally.

I can't use [k8s on terraform.io](https://registry.terraform.io/providers/mingfang/k8s/1.0.4) because i get:
<img width="951" alt="image" src="https://user-images.githubusercontent.com/43101981/224846438-3732d80d-bf07-4071-822e-97681f00d606.png">

**Comment by mingfang** [comment]
Please try release v1.0.6
