### ISSUE TITLE
Problems using provider

### ISSUE THREAD

**Issue by hassenius** [mingfang/terraform-provider-k8s#6]
Hi,

This provider looks very promising for us, as we are working on multiple different kubernetes/openshift clusters and distributions, so I wanted to evaluate it a bit more.
However, I seem to have some startup problems, and I suspect it's simply down to not configuring things correctly. Would you be able to point me towards where I'm going wrong.

Here's what I have
```15:19 $ terraform -v
Terraform v0.12.13
+ provider.aws v2.30.0
+ provider.k8s v0.1.1
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

15:22 $ file ~/.terraform.d/plugins/terraform-provider-k8s_v0.1.1 
~/.terraform.d/plugins/terraform-provider-k8s_v0.1.1: Mach-O 64-bit executable x86_64
```

Sample k8s_test.tf
```
data "k8s_core_v1_service" "httpbin" {
  metadata {
    name = "httpbin"
  }
}
```

Result
```
15:22 $ terraform plan

Error: Failed to instantiate provider "k8s" to obtain schema: Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.

```

**Comment by mingfang** [comment]
Can you please re-run the common with debug logging enabled?
```TF_LOG=DEBUG terraform apply```

I see this when the kubeconfig context is incorrect.

**Comment by mingfang** [comment]
Closing since I have not heard back.
I'm assuming this issue is resolved.
Please re-open otherwise.
