### ISSUE TITLE
Add support for OpenShift projects

### ISSUE THREAD

**Issue by patlachance** [mingfang/terraform-provider-k8s#7]
As a terraform-provider-k8s user
I would like to be able to create [projects](https://docs.openshift.com/container-platform/3.11/rest_api/apis-project.openshift.io/v1.Project.html) on OpenShift Container Platform
So that I could provision resources without being cluster admin

Creating namespace fails with the following error when trying to provision using an unprivileged user:

```
Error: namespaces is forbidden: User "unprivileged" cannot create namespaces at the cluster scope: no RBAC policy matched

  on main.tf line 1, in resource "k8s_core_v1_namespace" "this":
   1: resource "k8s_core_v1_namespace" "this" {
```

But unprivileged users can create their own namespaces using the "oc new-project myproject" command with oc client. Example:

1. Connect to openshift using a regular user

```
$ oc login https://console.{redacted} --token={redacted}
Logged into "https://console.{redacted}" as "unprivileged_user" using the token provided.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    project1
    project2
    project3
  
Using project "project2".
```

2. Create a new project, which is a regular kubernetes namespace with additional features:

```
$ oc new-project project4
Now using project "project4" on server "https://console.{redacted}".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app centos/ruby-25-centos7~https://github.com/sclorg/ruby-ex.git

to build a new example application in Ruby.
```

If you indicate how I can implement it myself, I can try and submit a PR.
I can also provide regular access (using personal message) to an OpenShift Container Platform for you to work on it.

**Comment by mingfang** [comment]
Calling Openshift specific APIs will be out of scope for this plugin.

However you can still use this plugin to use the namespaces, aka projects, created by the oc commands.  e.g.
```hcl
data "k8s_core_v1_namespace" "myproject" {
  metadata {
    name = "project4"
  }
}
```

**Comment by patlachance** [comment]
> Calling Openshift specific APIs will be out of scope for this plugin.
I understand

> However you can still use this plugin to use the namespaces, aka projects, created by the oc commands. e.g.
No. I tried to deploy [examples/nginx](https://github.com/mingfang/terraform-k8s-modules/tree/master/examples/nginx) and it fails if the token used in kubeconfig is not cluster-admin

I then tried to create the 'nginx-example' namespace using *oc* client and then run *terraform apply* but is tries to create or update the namespace which fails.

```
Terraform will perform the following actions:

  # k8s_core_v1_namespace.this will be created
  + resource "k8s_core_v1_namespace" "this" {
      + id = (known after apply)

      + metadata {
          + annotations                   = (known after apply)
          + creation_timestamp            = (known after apply)
          + deletion_grace_period_seconds = (known after apply)
          + deletion_timestamp            = (known after apply)
          + labels                        = {
              + "istio-injection" = "disabled"
            }
          + name                          = "nginx-example"
          + namespace                     = (known after apply)
          + resource_version              = (known after apply)
          + self_link                     = (known after apply)
          + uid                           = (known after apply)
        }

      + spec {}
    }

  # k8s_extensions_v1beta1_ingress.nginx will be created
...
...
```

So unfortunately none of your examples creating namespace work '*as-is*' on OpenShift with regular user.

**Comment by mingfang** [comment]
You're correct in that the examples will not run 'as-is' since they were not written for this specific use case.

If you use the oc command to create the namespace then you will get an error when running the examples that also tries to create the same namespace.
The solution is to replace the namespace resource with the data source as instructed above.

**Comment by patlachance** [comment]
> The solution is to replace the namespace resource with the data source as instructed above.

I tried but it fails. In fact fetching existing namespaces if not allowed for non 'cluster-admin' users, using the API nor *oc* client. Thus Terraform can't build the current state even if the namespace is already created.

Here is an example on [openshift-online](https://manage.openshift.com/)

```
$ oc get namespaces
No resources found.
Error from server (Forbidden): namespaces is forbidden: User "myonlineuser" cannot list resource "namespaces" in API group "" at the cluster scope
```

**Comment by mingfang** [comment]
It looks like the only option then is to grant read permission to the user for that namespace.

**Comment by mingfang** [comment]
Another thing to try is to remove the namespace resource and/or data source completely.
Then for the other resources, simply set the namespace field with the name,
 e.g. `namespace = "project4"`
or remove the namespace field altogether to use the default namespace.

**Comment by patlachance** [comment]
> Another thing to try is to remove the namespace resource and/or data source completely.
> Then for the other resources, simply set the namespace field with the name

Yes, that's what I did to confirm that I could deploy your nginx example after regenerating the archetypes in [this issue](https://github.com/mingfang/terraform-k8s-modules/issues/1).

But it means that complex examples or solutions using multiple namespaces could fail in the middle, leaving the environments in an unknown state. 

That's why I thought to extend this plugin to either use the "namespace" or the "project" resource, depending on the type of platform being used: *vanilla kubernetes* or *openshift*. I understand that examples / solutions you (and you community) provide would not work *as-is* but using simple sed command to replace "namespace" by "project" would allow users of the examples / solutions to *port* them from one platform to the other.

I'm ready to implement and make a PR, or create at terraform-provider-openshift extending this pluting if you prefer but simply don't know where to start.

**Comment by mingfang** [comment]
This plugin uses the official Kubernetes go-client for all it operations and will not be able to make Openshift specific API calls.  I think the best route forward is to create an entirely separate Terraform plugin for Openshift.

**Comment by patlachance** [comment]
Alright then, closing this issue. Thanks for your thoughts
